// Part 4 – Class Appointment  

//variables
public class Appointment {
    private String patientName;
    private String patientMobile;
    private String timeslot;
    private String HealthProfessional doctor; 


// constrcutor

    public Appointment() {
        this.patientName = "";
        this.patientMobile = "";
        this.timeslot = "";
        this.doctor = doctor;

 }

//inistalise the varribles 

    public Appointment(String patientName, String patientMobile, String timeslot, HealthProfessional doctor) {




   



    }


















}